### ISSUE TITLE
Possibility to exclude a feature from a list of constituent features

### ISSUE THREAD

**Issue by tidoust** [ddbeck/common-web-feature-mockup#4]
I like the idea of creating snapshot versions of features and of then reusing them to list additional features added afterwards, all the more so than I think the whole thing seems like it can be automated. Once in a while, a feature gets deprecated. It may be useful to have a way to exclude a constituent feature when referencing a snapshot, as in:

```yaml
constituentFeatures:
  - source: "bcd"
    query: "api.Navigator.someNewMediaThingThatDidntShipUntil2022"
  - source: "ddbeck/common-web-feature-mockup"
    query: "webrtc@2022 -api.Navigator.featureThatWasDeprecatedIn2022"
```

Probably low priority ;)
