### ISSUE TITLE
Encode editorial workflow information into a feature grouping

### ISSUE THREAD

**Issue by ddbeck** [ddbeck/common-web-feature-mockup#5]
Some feature groups may require lesser or greater degrees of authorship and editorial control. We ought to be able to signal to group maintainers and consumers what kind of status a given feature grouping has. That is to say, I think we can do better than a comment that says `GENERATED FILE DO NOT MODIFY` and the like.

Consider two extremes. A forthcoming feature may be composed of features selected entirely by hand (because of a lack of external data to reference and significant changes in the specification), while a snapshot of existing features might be entirely generated. We should be able to indicate to authors and consumers not just what a group contains, but how it came into being.

## Potential fields

Some possibilities follow.

### Status

For instance we might have a `status` field with a small number of blessed options, representing common states of change:

- `proposal` — a feature group before implementation, subject to arbitrary changes
- `active` — a feature group in the main lifecycle of implementation and support in shipping browser releases
- `generated` — a feature group with no direct human authorship (e.g., snapshots, catch-alls, etc.)
- `frozen` (or `retired`, `legacy`, `historic`) — to capture features which represent a point in time, but aren't expected to change in the future
- `pending-deletion` — a feature with expected removal in the future (e.g., an abandoned proposal, an unmaintained group, or a group that's been consolidated into a related group)

### Managers

We may want to be able identify who is responsible for a given feature grouping by listing editors for that feature. For example, we could have a list of editors, with a list of usernames, to give contributors a better idea of who talk to about changes or to drive review requests in the repository.

Here I've used the term "managers" to distinguish from, for example, specification editors. I am open to other terms though.

```YAML
managers:
  - @web-platform-dx/owners
  - @ddbeck 
  - @tidoust
  - etc.
  - [css-feature-group-updater]
  - [idl-parser-bot]
```

We could even tag specific automated processes as "editors", when some portion of the grouping is derived automatically.

### Other fields

Other fields might support workflow automation. Some possibilities could be dates:

- `created` 
- `lastReviewed`
- `lastModified`
- `expiration`

## Structure

Taken together, we might want to group this information together, so that it's clearer to consumers that these fields are *not* innate characteristics of the underlying features, but a description of our editorial process (i.e., a `pending-deletion` doesn't mean the features are expected to be removed, but our tracking of the grouping is).

For example:

```YAML
metadata:
  status: active
  managers:
    - @ddbeck 
    - @tidoust
    - @web-platform-dx/owners
    - [css-feature-group-updater]
    - [idl-parser-bot]
  created: 2022-10-17
  lastModified: 2022-10-17
  expiration: never
```

We might even want to extend this to individual `consitituentFeatures`, allowing them to be linked back to the workflow metadata:

```YAML
- source: bcd
  query: some.Generated.Feature
  managedBy:
  - idl-parser-bot  # only idl-parser-bot should get to modify this feature
```
